Repository computer-aided-biotech/better-cb, pull requests merged in 2020-10, with the labels that each got.

#6 feat: code of conduct
  .github/CODE_OF_CONDUCT.md
Labels: documentation

#4 Update 02.manuscript.md with outline
  content/02.manuscript.md
Labels: new section

#15 feat: new manuscript structure
  content/02.introduction.md
  content/02.manuscript.md
  content/03.personal-research.md
  content/04.collaboration.md
  content/05.community.md
  content/06.case-studies.md
  content/07.conclusion.md
  content/08.acknowledgments.md
Labels: standby
